# Generated by Django 5.2.1 on 2025-06-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psysmysql', '0002_alter_sell_datesell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='datesell',
            field=models.DateTimeField(auto_now=True, db_column='dateSell'),
        ),
    ]
