# Generated by Django 5.2.1 on 2025-07-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psysmysql', '0003_alter_sell_datesell'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistersellDetail',
            fields=[
                ('idsell', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('id_employed', models.CharField(max_length=150)),
                ('total_sell', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_pay', models.CharField(max_length=150)),
                ('state_sell', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True, max_length=200, null=True)),
                ('detail_sell', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Register_sell',
                'verbose_name_plural': 'Register_sells',
                'db_table': 'register_sells',
                'ordering': ['-date'],
            },
        ),
    ]
