# Generated by Django 5.1.7 on 2025-07-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psysmysql', '0004_registerselldetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerselldetail',
            name='detail_sell',
            field=models.JSONField(default=list),
        ),
    ]
