# Generated by Django 5.2.1 on 2025-07-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psysmysql', '0005_alter_registerselldetail_detail_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerselldetail',
            name='detail_sell',
            field=models.CharField(max_length=1000),
        ),
    ]
