# Generated by Django 5.2.1 on 2025-07-17 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psysmysql', '0007_alter_registerselldetail_detail_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='id_product',
            field=models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.CASCADE, to='psysmysql.products'),
        ),
    ]
