# Generated by Django 5.2.1 on 2025-07-17 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psysmysql', '0008_alter_sell_id_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='id_products',
            field=models.ForeignKey(db_column='id_Products', on_delete=django.db.models.deletion.CASCADE, to='psysmysql.products'),
        ),
    ]
