# Generated by Django 5.2.1 on 2025-07-17 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psysmysql', '0010_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='ciudad',
        ),
    ]
